### ISSUE TITLE
amazing work!! 

### ISSUE THREAD

**Issue by avierr** [dosyago/dumbass#73]
This is one of the best works I have seen, It takes a genius to keep things dumb!!

I really can't believe the complexity required these days to just render a fu***n list. 
And also don't get the people touting about render performance, you aren't building a AAA game title, majority of you would be just making lists and forms 🤦‍♂️

Would be nice to see how do we build very basic examples of:
- components
- properties 
- global state
- routing

**Comment by crislin2046** [comment]
thank you very much. I'll work on adding those examples.
